//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebaAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dia
    {
        public int IdDia { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Holiday { get; set; }
        public byte IsHoliday { get; set; }
        public string Color { get; set; }
    }
}
